# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBusiness():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_business(self):
    self.driver.get("http://code-server-app/Chainvest/BO/login")
    self.driver.set_window_size(1456, 876)
    self.driver.find_element(By.ID, "Email").click()
    self.driver.find_element(By.ID, "Email").send_keys("admin@chainvest.com")
    self.driver.find_element(By.ID, "Password").click()
    self.driver.find_element(By.ID, "Password").send_keys("P@ssw0rd")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Business").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .btn-primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .btn-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "Name").click()
    self.driver.find_element(By.ID, "BusinessTypeID").click()
    self.driver.find_element(By.ID, "BusinessTypeID").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid-cols-1").click()
    self.driver.find_element(By.ID, "Logo").click()
    self.driver.find_element(By.ID, "ContactPersonName").click()
    self.driver.find_element(By.ID, "EmailID").click()
    self.driver.find_element(By.ID, "MobileNo1").click()
    self.driver.find_element(By.ID, "MobileNo2").click()
    self.driver.find_element(By.ID, "WebsiteURL").click()
    self.driver.find_element(By.ID, "BusinessLicenseNo").click()
    self.driver.find_element(By.ID, "VAT").click()
    self.driver.find_element(By.ID, "Description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\!font-medium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
  
